apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-aws-vn02
  labels:
    app: ubuntu-aws-vn02
  annotations: {
    "opencontrail.org/network" : '{"domain":"default-domain", "project": "admin", "name":"VN-02"}'
  }
spec:
  nodeSelector:
    "kubernetes.io/hostname": "aws-contrail-k8s-node"
  containers:
    - name: ubuntuapp
      image: ubuntu-upstart